---
title: "Rich Lab for Molecular Health"
description: |
  Integrating Molecular Insights for Wildlife Conservation, Welfare, and Health
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    css: journal.css
site: distill::distill_website

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo    = FALSE,
  warning = FALSE,
  message = FALSE,
  comment = ""
  )
```


Welcome to the Rich Molecular Health Lab at the University of Nebraska Omaha! We integrate molecular ecology and physiology, bioinformatics, wildlife conservation, biomedical sciences, and population biology. This comprehensive, interdisciplinary approach allows us to enhance the health, welfare, and conservation of primates and other mammals. Our evidence-based strategies directly inform animal care practices and global conservation efforts.

---

## Research Focus

### Molecular Health and Conservation Genomics {.unlisted}

Our lab applies advanced genomic techniques to study mammalian health, welfare, and conservation:

- **Gut Microbiome and Chronic Disease Risk:** Investigating relationships between diet, microbiome composition, inflammation, and chronic disease in captive and wild primates.
- **Bioactive Foods and Receptor Physiology:** Examining plant compounds in diets and their impacts on primate reproduction and endocrine health.
- **Molecular Tools for Population Management:** Using portable sequencing technologies to perform rapid, low-cost, mitochondrial genome sequencing for improved species management and taxonomic revision.
- **Environmental DNA (eDNA) Monitoring:** Developing streamlined methods for non-invasive genetic monitoring of urban and wild North American mammalian populations.
- ***Heavy Metal Toxicity and Microbiome Buffering:*** Studying how heavy metals impact health and how gut microbiomes may mitigate toxic effects in zoo animals.

---


## Join Us!

Are you interested in joining or collaborating with our lab? We encourage you to explore our current projects and opportunities. You can reach out to the PI, Dr. Alicia Rich, via email to discuss potential collaborations. See the [profile of current lab members](about.html) if you are interested in pursuing graduate or undergraduate research in the lab.
